# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- charandev
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'myDockerhub-ServiceConnection'
    repository: 'charankumarcpl/pipeline'
    command: 'build'
    Dockerfile: '**/dockerfile'
- task: Docker@2
  inputs:
    containerRegistry: 'myDockerhub-ServiceConnection'
    repository: 'charankumarcpl/pipeline'
    command: 'push'